spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default
    username: username
    password: password
  profiles:
    active: dev

custom:
  datasource:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, custom

debug: false
